# Generated by Django 4.0.5 on 2022-06-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='age',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
